---
- hosts: all
  vars_files:
  - vars/local.yml
  become: yes

  tasks:
    - name: "Ensure python-pip is installed"
      apt:
        name: python-pip
        state: present

    - name: "Ensure pymysql is installed"
      command: pip install pymysql
  roles:
    - { name: ssh.copy, become: false, become_user: vagrant}
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php
    - app.source
    - app.phpmyadmin
