---

- name: Setting Up Ansible Main Server to Manage other Instances
  hosts: all
  remote_user: vagrant
  become: true
  vars_files:
    - ../../ansible/vars/directory_variables.yml


- tasks:
  - name: Generate the key for Machines
    command: ssh-keygen -t ed25519 -C "ansible" -f $HOME/.ssh/ansible_key



  - name: Copy the SSH Key to Every Instance
    copy:
      src: "$HOME/.ssh"

## Copy the SSH Key to EVERY INSTANCE
ssh-copy-id -i ~/.ssh/id_ed25519.pub <IP_ADDRESS>

## TOOD:
# - MAKE THIS SCRIPT ANSIBLE PLAYBOOK
# - STORE THE GENERATED KEYS IN .SSH DIRECTORY OF THE GITHUB
# - COPY THE PUBLIC KEYS TO ALL OF THE ANSIBLE INVENTORY HOSTS
# - MAKE IT A ROLE 